### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by jimfleming** [dwrensha/capnp-zmq-rust#1]
Hello!

I'm curious if this still works and if there are any gotchas for using. I'm evaluating using zmq with capnp and this is the only resource I could find for converting capnp streams to zmq messages or even byte slices.

**Comment by dwrensha** [comment]
Hi! Wow, this repo had some major bit rot. I've updated it and everything should work now.

**Comment by jimfleming** [comment]
That was quick, thanks!

I was just about to dive into these functions to see if it would remove some of that translation code: https://github.com/dwrensha/capnproto-rust/blob/master/src/lib.rs#L91
